---
{{- with .Values.nginx }}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    namespace: {{ $.Release.Namespace }}
    labels:
        app.kubernetes.io/instance: nginx
        app.kubernetes.io/name: nginx
spec:
    replicas: {{ .replicas }}
    selector:
        matchLabels:
            app.kubernetes.io/instance: nginx
            app.kubernetes.io/name: nginx
    template:
        metadata:
            labels:
                app.kubernetes.io/instance: nginx
                app.kubernetes.io/name: nginx
        spec:
            containers:
                -   name: nginx
                    image: {{ .image }}
                    securityContext:
                        privileged: false
                        allowPrivilegeEscalation: false
{{- if .resources }}
                    resources:
{{ toYaml .resources | indent 22 }}
{{- end }}
                    ports:
                        -   name: nginx
                            containerPort: {{ .port }}
                    livenessProbe:
                        failureThreshold: 2
                        initialDelaySeconds: 10
                        timeoutSeconds: 2
                        httpGet:
                            path: /
                            port: {{ .port }}
                    startupProbe:
                        failureThreshold: 5
                        timeoutSeconds: 2
                        httpGet:
                            path: /
                            port: {{ .port }}
{{- end }}