argocd-apps:
  applicationsets:
    apps:
      generators:
      - git:
          repoURL: https://github.com/pmonllor/k8s-gitops.git
          revision: HEAD
          directories:
          #- path: kubernetes/apps/*
          - path: kubernetes/argocd/*
      template:
        metadata:
          name: '{{path.basename}}'
          labels:
            project: 'default' # '{{path.basename}}'
          annotations: {}
        spec:
          project: default
          source:
            repoURL: https://github.com/pmonllor/k8s-gitops.git
            targetRevision: HEAD
            path: '{{path}}'
          destination:
            namespace: argocd #'{{path.basename}}'
            server: https://kubernetes.default.svc
          syncPolicy:
            automated:
              prune: false
              selfHeal: false
            syncOptions:
            - CreateNamespace=true
            - FailOnSharedResource=true