argocd-apps:
  applications:
    # Self-managed ArgoCD
    argocd:
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/pmonllor/k8s-gitops.git
        path: kubernetes/argocd
        targetRevision: HEAD
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
    # Self-managed App of Apps
    argocd-apps:
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/pmonllor/k8s-gitops.git
        path: kubernetes/argocd-apps
        targetRevision: HEAD
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
  applicationsets:
    # Applications in kubernetes/apps/ directory
    apps:
      generators:
      - git:
          repoURL: https://github.com/pmonllor/k8s-gitops.git
          revision: HEAD
          directories:
          - path: kubernetes/apps/*
      template:
        metadata:
          name: '{{path.basename}}'
          labels:
            project: 'default' # '{{path.basename}}'
          annotations: {}
        spec:
          project: default
          source:
            repoURL: https://github.com/pmonllor/k8s-gitops.git
            targetRevision: HEAD
            path: '{{path}}'
          destination:
            namespace: '{{path.basename}}'
            server: https://kubernetes.default.svc
          syncPolicy:
            automated:
              prune: false
              selfHeal: false
            syncOptions:
            - CreateNamespace=true
            - FailOnSharedResource=true