argocd-apps:
  applicationsets:
    # Applications in kubernetes/apps/ directory managed by ArgoCD
    apps:
      generators:
      - git:
          repoURL: https://github.com/pmonllor/k8s-gitops.git
          revision: HEAD
          directories:
          - path: kubernetes/apps/*
          - path: kubernetes/argocd/
          - path: kubernetes/argocd-apps/
      template:
        metadata:
          name: '{{path.basename}}'
          labels:
            project: 'default' # '{{path.basename}}'
          annotations: {}
        spec:
          project: default
          source:
            repoURL: https://github.com/pmonllor/k8s-gitops.git
            targetRevision: HEAD
            path: '{{path}}'
          destination:
            namespace: '{{path.basename}}'
            server: https://kubernetes.default.svc
          syncPolicy:
            automated:
              prune: false
              selfHeal: false
            syncOptions:
            - CreateNamespace=true
            - FailOnSharedResource=true